#!/bin/bash
source ./submodules/bootstrap/logging
set -euo pipefail ; IFS=$'\n\t'

#-----------
# Configurations
#-----------

ELIXIR_VERSION=${ELIXIR_VERSION-v1.0.0}

export EXRM_NAME=${EXRM_NAME-sampleexrm}
export EXRM_VERSION=${EXRM_VERSION-0.0.1}

EXRM_LOG_DIR=${EXRM_LOG_DIR-/var/log}
EXRM_PROXY_PORT=${EXRM_PROXY_PORT-80}
EXRM_LAUNCHER_DIR=${EXRM_LAUNCHER_DIR-/var/local/apps/${EXRM_NAME}}
EXRM_REPO=${EXRM_REPO-https://github.com/aforward/sampleexrm.git}
EXRM_HTTP_PORT=${EXRM_HTTP_PORT-80}
EXRM_SSL_PORT=${EXRM_SSL_PORT-443}
EXRM_APP_PORT=${EXRM_INTERNAL_PORT-$EXRM_HTTP_PORT}
EXRM_SERVER_NAMES=${EXRM_SERVER_NAMES-_}

#-----------
# Install Script
#-----------

notify "Install $EXRM_NAME ($EXRM_VERSION, elixir $ELIXIR_VERSION)..."

mkdir -p ${EXRM_LAUNCHER_DIR}/bin

TEMPLATE=./submodules/exrm/files/upgrade \
  LOCATION=${EXRM_LAUNCHER_DIR}/bin/upgrade \
  ./submodules/docker/copyif @EXRM_NAME@ $EXRM_NAME @EXRM_VERSION@ $EXRM_VERSION

TEMPLATE=./submodules/bootstrap/logging \
  LOCATION=${EXRM_LAUNCHER_DIR}/bin/logging \
  ./submodules/docker/copyif

cp ./submodules/exrm/files/exrm.dockerfile ${EXRM_LAUNCHER_DIR}/Dockerfile
cp ./submodules/exrm/files/exrm.dockerignore ${EXRM_LAUNCHER_DIR}/.dockerignore
sed -i s/@ELIXIR_VERSION@/$ELIXIR_VERSION/g ${EXRM_LAUNCHER_DIR}/Dockerfile
sed -i s/@EXRM_VERSION@/$EXRM_VERSION/g ${EXRM_LAUNCHER_DIR}/Dockerfile
sed -i "s|@EXRM_REPO@|$EXRM_REPO|g" ${EXRM_LAUNCHER_DIR}/Dockerfile
LAUNCHER_DIR=$EXRM_LAUNCHER_DIR NAME=$EXRM_NAME VERSION=$EXRM_VERSION ./submodules/docker/build

NAME=$EXRM_NAME IMAGE_NAME=${EXRM_NAME}:${EXRM_VERSION} DIR=$EXRM_LAUNCHER_DIR \
  START=./submodules/exrm/files/_start \
  DEBUG=./submodules/exrm/files/_debug \
  ./submodules/docker/helpers

notify "DONE, Install $EXRM_NAME ($EXRM_VERSION, elixir $ELIXIR_VERSION)"